### ISSUE TITLE
Delay needed for android

### ISSUE THREAD

**Issue by hpssjellis** [tejaswigowda/mediapipe-pose2bvh#4]
@tejaswigowda can you out a slight delay in the startup code so that the demo loads on android.

I get this error about the video source not starting then a few seconds later the video source starts.

![Screenshot_20241007_074012_Chrome](https://github.com/user-attachments/assets/fe69c76f-cfda-4820-82dc-c3d32d5fa9d4)

**Comment by tejaswigowda** [comment]
Done. added a 5 sec delay.

**Comment by tejaswigowda** [comment]
https://github.com/tejaswigowda/mediapipe-pose2bvh/blob/main/docs/script.js#L98-L100
